### ISSUE TITLE
[Chore] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by Kyxxn** [NostalgiaLocker/iOS#2]
## Issue
- 프로젝트 초기 세팅

## To-do

- [x] gitignore 세팅 (DS_Store, API KEY)
- [x] 이슈 템플릿 설정
- [x] PR 템플릿 설정
- [x] xcode 프로젝트 설정
